system:
  # 系统模式
  mode: "develop"
  exceptAuth:
    - "/login"
    - "/logout"
    - "/admin/member/info"
    - "/admin/menu/dynamic"
  superAdmin:
    # 超级管理员 (用户名: superAdmin)的密码，如果为空，则使用默认密码
    password: "123456"
  # 缓存配置
  cache:
    # 缓存适配器
    adapter: "file"
    # 文件缓存目录
    fileDir: "tmp/cache"
  # ---------------------
  # 登录相关的配置
  token:
    # 令牌的过期时间，单位: 秒
    expires: 86400
    # 令牌的刷新时间，单位: 秒
    refreshInterval: 3600
    # 令牌的最大刷新次数
    maxRefreshTimes: 10
    # 令牌的密钥
    secretKey: "zzframe"
    # 是否允许多端登录
    multiLogin: true


# Database. 配置参考：https://goframe.org/pages/viewpage.action?pageId=1114245
database:
  logger:
    path: "logs/database"                       # 日志文件路径。默认为空，表示关闭，仅输出到终端
    stdout: true
  default:
    link: "mysql:root:nieliehai123456@tcp(129.204.199.135:3306)/zz-frame-dev?loc=Local&parseTime=true&charset=utf8mb4"
    debug: true
    Prefix: "zz_"
  