
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:nieliehai123456@tcp(129.204.199.135:3306)/zz-frame-dev"
        descriptionTag: true
        removePrefix: "zz_" # 移除前缀
        noModelComment: true # 是否不添加模型注释
        jsonCase: "CamelLower" # 驼峰命名
        gJsonSupport: true # 是否支持gjson
        clear: false # 是否清除

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app